# Generated by Django 5.2.4 on 2025-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='blog/images/some_one.jpg', null=True, upload_to='profile_pics/'),
        ),
    ]
